### ISSUE TITLE
libswiftQuartzCore.dylib Library not loaded in 1.20

### ISSUE THREAD

**Issue by davidkaufman** [Lord-Kamina/Deluge-Magnet-Handler#3]
Downloaded 1.2.0, installed to /Applications/ and tried it out, and got the error:

  dyld: Library not loaded: @rpath/libswiftQuartzCore.dylib
  Referenced from: /Applications/Magnet Handler.app/Contents/Resources/registerHandler
  Reason: image not found

I'm running OS X El Capitan version 10.11.6 (15G1108)
on a MacBook Pro (Retina, Mid 2012) 2.7 GHz Intel Core i7 16 GB

Is this only for Sierra?

**Comment by Lord-Kamina** [comment]
That's probably an error on my part; nonetheless, 1.2.0 was made for Sierra, the previous version should work fine on El Capitan.

**Comment by davidkaufman** [comment]
Version 1.2.1 works for me on El Capitan 10.11.6 -- thanks!
